version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/PolyDeploy"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/DeployClient"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
