name: CI (Build and Package)

on:
  workflow_dispatch:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

defaults:
  run:
    shell: pwsh

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]
        node-version: [14.x]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.3
    
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: latest
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.4.0
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install npm modules
      run: |
        cd DeployClient
        npm ci
        cd ../PolyDeploy
        npm ci
        cd ..

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build and package the application
      run: msbuild PolyDeploy.sln /m /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
      
    - name: Publish Deploy Client
      run: dotnet publish PolyDeploy.DeployClient/PolyDeploy.DeployClient.csproj --configuration ${{ matrix.configuration }} --no-build --output dist/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        path: dist/
