name: CI (Build and Package)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: pwsh

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]
        node-version: [12.x]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.2
      with:
        nuget-version: latest
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install npm modules
      run: |
        cd DeployClient
        npm ci
        cd ../PolyDeploy
        npm ci
        cd ..

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build and package the application
      run: msbuild PolyDeploy.sln /m /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        path: ../../CompiledModules/
